# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/adc/adc.srcs/sources_1/bd/projectHW/ip/projectHW_dds_compiler_0_1/projectHW_dds_compiler_0_1.xci
# IP: The module: 'projectHW_dds_compiler_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/adc/adc.gen/sources_1/bd/projectHW/ip/projectHW_dds_compiler_0_1/projectHW_dds_compiler_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'projectHW_dds_compiler_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/adc/adc.srcs/sources_1/bd/projectHW/ip/projectHW_dds_compiler_0_1/projectHW_dds_compiler_0_1.xci
# IP: The module: 'projectHW_dds_compiler_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/adc/adc.gen/sources_1/bd/projectHW/ip/projectHW_dds_compiler_0_1/projectHW_dds_compiler_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'projectHW_dds_compiler_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
