# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/projectHW/projectHW.srcs/sources_1/bd/projectHW/ip/projectHW_DAC2_BUF_OUT_0/projectHW_DAC2_BUF_OUT_0.xci
# IP: The module: 'projectHW_DAC2_BUF_OUT_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/projectHW/projectHW.gen/sources_1/bd/projectHW/ip/projectHW_DAC2_BUF_OUT_0/projectHW_DAC2_BUF_OUT_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'projectHW_DAC2_BUF_OUT_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/projectHW/projectHW.gen/sources_1/bd/projectHW/ip/projectHW_DAC2_BUF_OUT_0/projectHW_DAC2_BUF_OUT_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'projectHW_DAC2_BUF_OUT_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/projectHW/projectHW.srcs/sources_1/bd/projectHW/ip/projectHW_DAC2_BUF_OUT_0/projectHW_DAC2_BUF_OUT_0.xci
# IP: The module: 'projectHW_DAC2_BUF_OUT_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/projectHW/projectHW.gen/sources_1/bd/projectHW/ip/projectHW_DAC2_BUF_OUT_0/projectHW_DAC2_BUF_OUT_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'projectHW_DAC2_BUF_OUT_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/projectHW/projectHW.gen/sources_1/bd/projectHW/ip/projectHW_DAC2_BUF_OUT_0/projectHW_DAC2_BUF_OUT_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'projectHW_DAC2_BUF_OUT_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
