# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/projectHW/projectHW.srcs/sources_1/bd/projectHW/ip/projectHW_clk_div2_0/projectHW_clk_div2_0.xci
# IP: The module: 'projectHW_clk_div2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/projectHW/projectHW.gen/sources_1/bd/projectHW/ip/projectHW_clk_div2_0/projectHW_clk_div2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'projectHW_clk_div2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/projectHW/projectHW.srcs/sources_1/bd/projectHW/ip/projectHW_clk_div2_0/projectHW_clk_div2_0.xci
# IP: The module: 'projectHW_clk_div2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/projectHW/projectHW.gen/sources_1/bd/projectHW/ip/projectHW_clk_div2_0/projectHW_clk_div2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'projectHW_clk_div2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
