# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/constrs/REV.xdc

# Block Designs: bd/projectHW/projectHW.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW || ORIG_REF_NAME==projectHW} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_DAC1_BUF_OUT_0/projectHW_DAC1_BUF_OUT_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_DAC1_BUF_OUT_0 || ORIG_REF_NAME==projectHW_DAC1_BUF_OUT_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_DAC2_BUF_OUT_0/projectHW_DAC2_BUF_OUT_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_DAC2_BUF_OUT_0 || ORIG_REF_NAME==projectHW_DAC2_BUF_OUT_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_FPGA_CLK_BUF_0/projectHW_FPGA_CLK_BUF_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_FPGA_CLK_BUF_0 || ORIG_REF_NAME==projectHW_FPGA_CLK_BUF_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_DAC2_CTRL_0/projectHW_DAC2_CTRL_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_DAC2_CTRL_0 || ORIG_REF_NAME==projectHW_DAC2_CTRL_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_dds_compiler_0_0/projectHW_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_dds_compiler_0_0 || ORIG_REF_NAME==projectHW_dds_compiler_0_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_axi_interconnect_0_0/projectHW_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_axi_interconnect_0_0 || ORIG_REF_NAME==projectHW_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_ila_1_0/projectHW_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_ila_1_0 || ORIG_REF_NAME==projectHW_ila_1_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_proc_sys_reset_0_0/projectHW_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_proc_sys_reset_0_0 || ORIG_REF_NAME==projectHW_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_processing_system7_0_0/projectHW_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_processing_system7_0_0 || ORIG_REF_NAME==projectHW_processing_system7_0_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_xlconcat_0_0/projectHW_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_xlconcat_0_0 || ORIG_REF_NAME==projectHW_xlconcat_0_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_DDS_CTRL_AB_0/projectHW_DDS_CTRL_AB_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_DDS_CTRL_AB_0 || ORIG_REF_NAME==projectHW_DDS_CTRL_AB_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_xlconcat_0_1/projectHW_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_xlconcat_0_1 || ORIG_REF_NAME==projectHW_xlconcat_0_1} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_xlconstant_0_0/projectHW_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_xlconstant_0_0 || ORIG_REF_NAME==projectHW_xlconstant_0_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_c_counter_binary_0_0/projectHW_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_c_counter_binary_0_0 || ORIG_REF_NAME==projectHW_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_xlslice_0_0/projectHW_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_xlslice_0_0 || ORIG_REF_NAME==projectHW_xlslice_0_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_clkdiv2_0/projectHW_clkdiv2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_clkdiv2_0 || ORIG_REF_NAME==projectHW_clkdiv2_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_dds_compiler_0_1/projectHW_dds_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_dds_compiler_0_1 || ORIG_REF_NAME==projectHW_dds_compiler_0_1} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_interleave_0_0/projectHW_interleave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_interleave_0_0 || ORIG_REF_NAME==projectHW_interleave_0_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_xbar_0/projectHW_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_xbar_0 || ORIG_REF_NAME==projectHW_xbar_0} -quiet] -quiet

# IP: bd/projectHW/ip/projectHW_auto_pc_0/projectHW_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==projectHW_auto_pc_0 || ORIG_REF_NAME==projectHW_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/shtomer/WIS_work/WIP/build_Test/projectHW_ADC_build/adc/adc.gen/sources_1/bd/projectHW/projectHW_ooc.xdc
